# post http://localhost:8080/admin/create/application/1/2

# get http://localhost:8080/admin/applications?indexId=10&limit=12

# get http://localhost:8080/admin/jobs?indexId=3&limit=12

delete http://localhost:8080/admin/delete/application/1
###

get http://localhost:8080/admin/companies?indexId=2&limit=8
###

# get http://localhost:8080/admin/companyNames

POST http://localhost:8080/admin/create/job
content-type: application/json

{
    "companyId": 3,
    "title": "Head of Cars",
    "wage": 40000,
    "location": "Reading",
    "jobType": "Interim",
    "position": "In House",
    "pqe": 2,
    "featured": 0,
    "description": "This is a description"

}

###

###
POST http://localhost:8080/admin/create/company
content-type: application/json

{
    "companyName": "Lloyds",
    "firstName": "Nick",
    "lastName": "Woodward",
    "position": "CEO",
    "phone": "07484312767",
    "email": "t1gg2d@hotmail.com",
    "firstLine": "4 Meadow Road",
    "city": "Reading",
    "county": "Berks",
    "postcode": "RG77WA"
}

###

POST http://localhost:8080/admin/create/contact
content-type: application/json

{
    "companyId": "1",
    "firstName": "Nick",
    "lastName": "Woodward",
    "position": "CEO",
    "phone": "07484312767",
    "email": "nickwoodward@hotmail.com"
}

###

POST http://localhost:8080/admin/create/address
content-type: application/json

{
    "id":"1",
    "firstLine":"4 Meadow Road",
    "city": "Pewsey",
    "county": "Wiltshire",
    "postcode": "RG6 8EU"
}

###

POST http://localhost:8080/admin/edit/company
content-type: application/json

{
    "id": "4",
    "contactId":"6",
    "addressId":"3",
    "companyName": "Test",
    "firstName": "Phil",
    "lastName": "Woodward",
    "position": "CEO",
    "phone": "07484312767",
    "email": "nickwoodward@hotmail.com",
    "firstLine": "4 Meadow Road",
    "secondLine": "test",
    "city": "Reading",
    "county": "Berks",
    "postcode": "RG77WA"
}
###

POST http://localhost:8080/admin/edit/contact
content-type: application/json

{
    "id": "4",
    "contactId":"5",
    "firstName": "Jon",
    "lastName": "Woodward",
    "position": "CEO",
    "phone": "07484312767",
    "email": "nickwoodward@gmai.com"
}
###

POST http://localhost:8080/admin/edit/address
content-type: application/json

{
    "id":"2",
    "addressId":"4",
    "firstLine": "4 Meadow Road",
    "secondLine": "test",
    "city": "Reading",
    "county": "Berks",
    "postcode": "RG77WA"
}

###

DELETE http://localhost:8080/admin/delete/company/2
###

DELETE http://localhost:8080/admin/delete/address/2
###

DELETE http://localhost:8080/admin/delete/contact/3
###

GET http://localhost:8080/admin/jobnames
###

GET http://localhost:8080/admin/applicants
###

POST http://localhost:8080/admin/create/applicant
content-type: application/json

{
    "firstName": "Jon",
    "lastName": "Woodward",
    "position": "CEO",
    "phone": "07484312767",
    "email": "nickwoodward@gmaild.com"
}